# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chang Kong
email: 515975663@qq.com

#write html inside the double quotes to display in jumbotron
description: "<h3>00 01 10 11</h3><h1>长空博客</h1><h3>世界这么大，那里都一样！</h3>unity3d专业技术分享！"



baseurl: "" # the subpath of your site, e.g. /blog
url: "www.anthroposcopy.com" # the base hostname & protocol for your site
twitter_username: jack20000
github_username:  jack20000

# Build settings
markdown: kramdown
